global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'skystore-alerts'

receivers:
  - name: 'skystore-alerts'
    webhook_configs:
      - url: 'http://host.containers.internal:5001/api/alerts'
        send_resolved: true
        max_alerts: 10

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
