apiVersion: 1

datasources:
  # 1. مصدر مقاييس النظام والـ JVM
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://skystore-prometheus:9090
    isDefault: true
    editable: false

  # 2. مصدر السجلات المركزية
  - name: Loki
    type: loki
    access: proxy
    url: http://skystore-loki:3100
    isDefault: false
    editable: false
