apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-ms
  template:
    metadata:
      labels:
        app: orders-ms
    spec:
      containers:
        - name: orders-service
          image: orders-service:v2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_HOST
              value: "orders-db"
            - name: DATABASE_NAME
              value: "orders_db"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "zafer4519932093"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: ZIPKIN_URL
              value: "http://zipkin:9411/api/v2/spans"
