apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3009
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_HOST
              value: "payment-db"
            - name: DATABASE_NAME
              value: "payment_db"
            - name: DATABASE_USER
              value: "postgres"
            - name: DATABASE_PASSWORD
              value: "zafer4519932093"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
