apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-db
  template:
    metadata:
      labels:
        app: warehouse-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "zafer4519932093"
            - name: POSTGRES_DB
              value: "warehouse_db"
          volumeMounts:
            - name: warehouse-db-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: warehouse-db-data
          persistentVolumeClaim:
            claimName: warehouse-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-db
spec:
  selector:
    app: warehouse-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
