events {}

http {
    upstream auth_service {
        server auth-ms:3001;
    }
    upstream products_service {
        server products-ms:3002;
    }
    upstream orders_service {
        server orders-ms:3003;
    }

    server {
        listen 80;

        # CORS Configuration
        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type' always;

        # Handle Preflight OPTIONS requests for all routes
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        location /auth/ {
            proxy_pass http://auth_service/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /products {
            proxy_pass http://products_service/api/products;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /orders {
            proxy_pass http://orders_service/api/orders;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
